// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();
}
