// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

/**
 * Protobuf type {@code Log}
 */
public final class Log extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Log)
    LogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Log.newBuilder() to construct.
  private Log(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Log() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Log();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lql.raft.rpc.proto.NodeProto.internal_static_Log_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lql.raft.rpc.proto.NodeProto.internal_static_Log_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lql.raft.rpc.proto.Log.class, com.lql.raft.rpc.proto.Log.Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private long index_ = 0L;
  /**
   * <code>int64 index = 1;</code>
   * @return The index.
   */
  @java.lang.Override
  public long getIndex() {
    return index_;
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private long term_ = 0L;
  /**
   * <code>int64 term = 2;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int OPERATE_FIELD_NUMBER = 3;
  private com.lql.raft.rpc.proto.Operate operate_;
  /**
   * <code>.Operate operate = 3;</code>
   * @return Whether the operate field is set.
   */
  @java.lang.Override
  public boolean hasOperate() {
    return operate_ != null;
  }
  /**
   * <code>.Operate operate = 3;</code>
   * @return The operate.
   */
  @java.lang.Override
  public com.lql.raft.rpc.proto.Operate getOperate() {
    return operate_ == null ? com.lql.raft.rpc.proto.Operate.getDefaultInstance() : operate_;
  }
  /**
   * <code>.Operate operate = 3;</code>
   */
  @java.lang.Override
  public com.lql.raft.rpc.proto.OperateOrBuilder getOperateOrBuilder() {
    return operate_ == null ? com.lql.raft.rpc.proto.Operate.getDefaultInstance() : operate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (index_ != 0L) {
      output.writeInt64(1, index_);
    }
    if (term_ != 0L) {
      output.writeInt64(2, term_);
    }
    if (operate_ != null) {
      output.writeMessage(3, getOperate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (index_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, index_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, term_);
    }
    if (operate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOperate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lql.raft.rpc.proto.Log)) {
      return super.equals(obj);
    }
    com.lql.raft.rpc.proto.Log other = (com.lql.raft.rpc.proto.Log) obj;

    if (getIndex()
        != other.getIndex()) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (hasOperate() != other.hasOperate()) return false;
    if (hasOperate()) {
      if (!getOperate()
          .equals(other.getOperate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIndex());
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    if (hasOperate()) {
      hash = (37 * hash) + OPERATE_FIELD_NUMBER;
      hash = (53 * hash) + getOperate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lql.raft.rpc.proto.Log parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.lql.raft.rpc.proto.Log parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.lql.raft.rpc.proto.Log parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lql.raft.rpc.proto.Log parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lql.raft.rpc.proto.Log prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Log}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Log)
      com.lql.raft.rpc.proto.LogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_Log_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lql.raft.rpc.proto.Log.class, com.lql.raft.rpc.proto.Log.Builder.class);
    }

    // Construct using com.lql.raft.rpc.proto.Log.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      index_ = 0L;
      term_ = 0L;
      operate_ = null;
      if (operateBuilder_ != null) {
        operateBuilder_.dispose();
        operateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_Log_descriptor;
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.Log getDefaultInstanceForType() {
      return com.lql.raft.rpc.proto.Log.getDefaultInstance();
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.Log build() {
      com.lql.raft.rpc.proto.Log result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.Log buildPartial() {
      com.lql.raft.rpc.proto.Log result = new com.lql.raft.rpc.proto.Log(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.lql.raft.rpc.proto.Log result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.index_ = index_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.operate_ = operateBuilder_ == null
            ? operate_
            : operateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lql.raft.rpc.proto.Log) {
        return mergeFrom((com.lql.raft.rpc.proto.Log)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lql.raft.rpc.proto.Log other) {
      if (other == com.lql.raft.rpc.proto.Log.getDefaultInstance()) return this;
      if (other.getIndex() != 0L) {
        setIndex(other.getIndex());
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.hasOperate()) {
        mergeOperate(other.getOperate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              index_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getOperateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long index_ ;
    /**
     * <code>int64 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public long getIndex() {
      return index_;
    }
    /**
     * <code>int64 index = 1;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(long value) {

      index_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      index_ = 0L;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 2;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {

      term_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      term_ = 0L;
      onChanged();
      return this;
    }

    private com.lql.raft.rpc.proto.Operate operate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lql.raft.rpc.proto.Operate, com.lql.raft.rpc.proto.Operate.Builder, com.lql.raft.rpc.proto.OperateOrBuilder> operateBuilder_;
    /**
     * <code>.Operate operate = 3;</code>
     * @return Whether the operate field is set.
     */
    public boolean hasOperate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.Operate operate = 3;</code>
     * @return The operate.
     */
    public com.lql.raft.rpc.proto.Operate getOperate() {
      if (operateBuilder_ == null) {
        return operate_ == null ? com.lql.raft.rpc.proto.Operate.getDefaultInstance() : operate_;
      } else {
        return operateBuilder_.getMessage();
      }
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public Builder setOperate(com.lql.raft.rpc.proto.Operate value) {
      if (operateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operate_ = value;
      } else {
        operateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public Builder setOperate(
        com.lql.raft.rpc.proto.Operate.Builder builderForValue) {
      if (operateBuilder_ == null) {
        operate_ = builderForValue.build();
      } else {
        operateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public Builder mergeOperate(com.lql.raft.rpc.proto.Operate value) {
      if (operateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          operate_ != null &&
          operate_ != com.lql.raft.rpc.proto.Operate.getDefaultInstance()) {
          getOperateBuilder().mergeFrom(value);
        } else {
          operate_ = value;
        }
      } else {
        operateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public Builder clearOperate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      operate_ = null;
      if (operateBuilder_ != null) {
        operateBuilder_.dispose();
        operateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public com.lql.raft.rpc.proto.Operate.Builder getOperateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getOperateFieldBuilder().getBuilder();
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    public com.lql.raft.rpc.proto.OperateOrBuilder getOperateOrBuilder() {
      if (operateBuilder_ != null) {
        return operateBuilder_.getMessageOrBuilder();
      } else {
        return operate_ == null ?
            com.lql.raft.rpc.proto.Operate.getDefaultInstance() : operate_;
      }
    }
    /**
     * <code>.Operate operate = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lql.raft.rpc.proto.Operate, com.lql.raft.rpc.proto.Operate.Builder, com.lql.raft.rpc.proto.OperateOrBuilder> 
        getOperateFieldBuilder() {
      if (operateBuilder_ == null) {
        operateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lql.raft.rpc.proto.Operate, com.lql.raft.rpc.proto.Operate.Builder, com.lql.raft.rpc.proto.OperateOrBuilder>(
                getOperate(),
                getParentForChildren(),
                isClean());
        operate_ = null;
      }
      return operateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Log)
  }

  // @@protoc_insertion_point(class_scope:Log)
  private static final com.lql.raft.rpc.proto.Log DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lql.raft.rpc.proto.Log();
  }

  public static com.lql.raft.rpc.proto.Log getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Log>
      PARSER = new com.google.protobuf.AbstractParser<Log>() {
    @java.lang.Override
    public Log parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Log> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Log> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lql.raft.rpc.proto.Log getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

