// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

public interface LogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Log)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 index = 1;</code>
   * @return The index.
   */
  long getIndex();

  /**
   * <code>int64 term = 2;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>.Operate operate = 3;</code>
   * @return Whether the operate field is set.
   */
  boolean hasOperate();
  /**
   * <code>.Operate operate = 3;</code>
   * @return The operate.
   */
  com.lql.raft.rpc.proto.Operate getOperate();
  /**
   * <code>.Operate operate = 3;</code>
   */
  com.lql.raft.rpc.proto.OperateOrBuilder getOperateOrBuilder();
}
