// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

public final class NodeProto {
  private NodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnode.proto\"k\n\tVoteParam\022\014\n\004term\030\001 \001(\003\022" +
      "\020\n\010serverId\030\002 \001(\t\022\023\n\013candidateId\030\003 \001(\t\022\024" +
      "\n\014lastLogIndex\030\004 \001(\003\022\023\n\013lastLogTerm\030\005 \001(" +
      "\003\"1\n\014VoteResponse\022\014\n\004term\030\001 \001(\003\022\023\n\013voteG" +
      "ranted\030\002 \001(\0102@\n\022ConsistencyService\022*\n\013vo" +
      "teRequest\022\n.VoteParam\032\r.VoteResponse\"\000B%" +
      "\n\026com.lql.raft.rpc.protoB\tNodeProtoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_VoteParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VoteParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteParam_descriptor,
        new java.lang.String[] { "Term", "ServerId", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteResponse_descriptor,
        new java.lang.String[] { "Term", "VoteGranted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
