// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

public interface VoteParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoteParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 候选人的任期号
   * </pre>
   *
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <pre>
   * 节点服务id(自定义)
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The serverId.
   */
  java.lang.String getServerId();
  /**
   * <pre>
   * 节点服务id(自定义)
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The bytes for serverId.
   */
  com.google.protobuf.ByteString
      getServerIdBytes();

  /**
   * <pre>
   * 请求选票的候选人id
   * </pre>
   *
   * <code>string candidateId = 3;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <pre>
   * 请求选票的候选人id
   * </pre>
   *
   * <code>string candidateId = 3;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <pre>
   * 候选人最后日志条目的索引值
   * </pre>
   *
   * <code>int64 lastLogIndex = 4;</code>
   * @return The lastLogIndex.
   */
  long getLastLogIndex();

  /**
   * <pre>
   * 候选人最后日志条目的任期号
   * </pre>
   *
   * <code>int64 lastLogTerm = 5;</code>
   * @return The lastLogTerm.
   */
  long getLastLogTerm();
}
