// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

/**
 * Protobuf type {@code VoteParam}
 */
public final class VoteParam extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VoteParam)
    VoteParamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VoteParam.newBuilder() to construct.
  private VoteParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoteParam() {
    serverId_ = "";
    candidateId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VoteParam();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lql.raft.rpc.proto.NodeProto.internal_static_VoteParam_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lql.raft.rpc.proto.NodeProto.internal_static_VoteParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lql.raft.rpc.proto.VoteParam.class, com.lql.raft.rpc.proto.VoteParam.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private long term_ = 0L;
  /**
   * <pre>
   * 候选人的任期号
   * </pre>
   *
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int SERVERID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverId_ = "";
  /**
   * <pre>
   * 节点服务id(自定义)
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The serverId.
   */
  @java.lang.Override
  public java.lang.String getServerId() {
    java.lang.Object ref = serverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 节点服务id(自定义)
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The bytes for serverId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerIdBytes() {
    java.lang.Object ref = serverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATEID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidateId_ = "";
  /**
   * <pre>
   * 请求选票的候选人id
   * </pre>
   *
   * <code>string candidateId = 3;</code>
   * @return The candidateId.
   */
  @java.lang.Override
  public java.lang.String getCandidateId() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求选票的候选人id
   * </pre>
   *
   * <code>string candidateId = 3;</code>
   * @return The bytes for candidateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateIdBytes() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTLOGINDEX_FIELD_NUMBER = 4;
  private long lastLogIndex_ = 0L;
  /**
   * <pre>
   * 候选人最后日志条目的索引值
   * </pre>
   *
   * <code>int64 lastLogIndex = 4;</code>
   * @return The lastLogIndex.
   */
  @java.lang.Override
  public long getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LASTLOGTERM_FIELD_NUMBER = 5;
  private long lastLogTerm_ = 0L;
  /**
   * <pre>
   * 候选人最后日志条目的任期号
   * </pre>
   *
   * <code>int64 lastLogTerm = 5;</code>
   * @return The lastLogTerm.
   */
  @java.lang.Override
  public long getLastLogTerm() {
    return lastLogTerm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0L) {
      output.writeInt64(1, term_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serverId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, candidateId_);
    }
    if (lastLogIndex_ != 0L) {
      output.writeInt64(4, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      output.writeInt64(5, lastLogTerm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, term_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serverId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, candidateId_);
    }
    if (lastLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, lastLogTerm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lql.raft.rpc.proto.VoteParam)) {
      return super.equals(obj);
    }
    com.lql.raft.rpc.proto.VoteParam other = (com.lql.raft.rpc.proto.VoteParam) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (!getServerId()
        .equals(other.getServerId())) return false;
    if (!getCandidateId()
        .equals(other.getCandidateId())) return false;
    if (getLastLogIndex()
        != other.getLastLogIndex()) return false;
    if (getLastLogTerm()
        != other.getLastLogTerm()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId().hashCode();
    hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId().hashCode();
    hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogIndex());
    hash = (37 * hash) + LASTLOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogTerm());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.lql.raft.rpc.proto.VoteParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.lql.raft.rpc.proto.VoteParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lql.raft.rpc.proto.VoteParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lql.raft.rpc.proto.VoteParam prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VoteParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VoteParam)
      com.lql.raft.rpc.proto.VoteParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_VoteParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_VoteParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lql.raft.rpc.proto.VoteParam.class, com.lql.raft.rpc.proto.VoteParam.Builder.class);
    }

    // Construct using com.lql.raft.rpc.proto.VoteParam.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      term_ = 0L;
      serverId_ = "";
      candidateId_ = "";
      lastLogIndex_ = 0L;
      lastLogTerm_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lql.raft.rpc.proto.NodeProto.internal_static_VoteParam_descriptor;
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.VoteParam getDefaultInstanceForType() {
      return com.lql.raft.rpc.proto.VoteParam.getDefaultInstance();
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.VoteParam build() {
      com.lql.raft.rpc.proto.VoteParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lql.raft.rpc.proto.VoteParam buildPartial() {
      com.lql.raft.rpc.proto.VoteParam result = new com.lql.raft.rpc.proto.VoteParam(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.lql.raft.rpc.proto.VoteParam result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serverId_ = serverId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.candidateId_ = candidateId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastLogIndex_ = lastLogIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastLogTerm_ = lastLogTerm_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lql.raft.rpc.proto.VoteParam) {
        return mergeFrom((com.lql.raft.rpc.proto.VoteParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lql.raft.rpc.proto.VoteParam other) {
      if (other == com.lql.raft.rpc.proto.VoteParam.getDefaultInstance()) return this;
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (!other.getServerId().isEmpty()) {
        serverId_ = other.serverId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCandidateId().isEmpty()) {
        candidateId_ = other.candidateId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getLastLogIndex() != 0L) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLastLogTerm() != 0L) {
        setLastLogTerm(other.getLastLogTerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              serverId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              candidateId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              lastLogIndex_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              lastLogTerm_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long term_ ;
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>int64 term = 1;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>int64 term = 1;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {

      term_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>int64 term = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      term_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object serverId_ = "";
    /**
     * <pre>
     * 节点服务id(自定义)
     * </pre>
     *
     * <code>string serverId = 2;</code>
     * @return The serverId.
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 节点服务id(自定义)
     * </pre>
     *
     * <code>string serverId = 2;</code>
     * @return The bytes for serverId.
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 节点服务id(自定义)
     * </pre>
     *
     * <code>string serverId = 2;</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 节点服务id(自定义)
     * </pre>
     *
     * <code>string serverId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      serverId_ = getDefaultInstance().getServerId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 节点服务id(自定义)
     * </pre>
     *
     * <code>string serverId = 2;</code>
     * @param value The bytes for serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object candidateId_ = "";
    /**
     * <pre>
     * 请求选票的候选人id
     * </pre>
     *
     * <code>string candidateId = 3;</code>
     * @return The candidateId.
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 请求选票的候选人id
     * </pre>
     *
     * <code>string candidateId = 3;</code>
     * @return The bytes for candidateId.
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求选票的候选人id
     * </pre>
     *
     * <code>string candidateId = 3;</code>
     * @param value The candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidateId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求选票的候选人id
     * </pre>
     *
     * <code>string candidateId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateId() {
      candidateId_ = getDefaultInstance().getCandidateId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求选票的候选人id
     * </pre>
     *
     * <code>string candidateId = 3;</code>
     * @param value The bytes for candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidateId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long lastLogIndex_ ;
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>int64 lastLogIndex = 4;</code>
     * @return The lastLogIndex.
     */
    @java.lang.Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>int64 lastLogIndex = 4;</code>
     * @param value The lastLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogIndex(long value) {

      lastLogIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>int64 lastLogIndex = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogTerm_ ;
    /**
     * <pre>
     * 候选人最后日志条目的任期号
     * </pre>
     *
     * <code>int64 lastLogTerm = 5;</code>
     * @return The lastLogTerm.
     */
    @java.lang.Override
    public long getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <pre>
     * 候选人最后日志条目的任期号
     * </pre>
     *
     * <code>int64 lastLogTerm = 5;</code>
     * @param value The lastLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogTerm(long value) {

      lastLogTerm_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人最后日志条目的任期号
     * </pre>
     *
     * <code>int64 lastLogTerm = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastLogTerm_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VoteParam)
  }

  // @@protoc_insertion_point(class_scope:VoteParam)
  private static final com.lql.raft.rpc.proto.VoteParam DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lql.raft.rpc.proto.VoteParam();
  }

  public static com.lql.raft.rpc.proto.VoteParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteParam>
      PARSER = new com.google.protobuf.AbstractParser<VoteParam>() {
    @java.lang.Override
    public VoteParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoteParam> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteParam> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lql.raft.rpc.proto.VoteParam getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

