// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package com.lql.raft.rpc.proto;

public interface VoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 当前任期号
   * </pre>
   *
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <pre>
   * 当候选人赢得该节点投票时为true
   * </pre>
   *
   * <code>bool voteGranted = 2;</code>
   * @return The voteGranted.
   */
  boolean getVoteGranted();
}
